# Generated by Django 3.0.5 on 2020-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relyear', models.IntegerField()),
                ('movname', models.CharField(max_length=10)),
                ('hero', models.CharField(max_length=10)),
                ('heroine', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
